version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - python3 -m pip install sphinx_rtd_theme



sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true